const SUPABASE_URL="https://wwiovsfkmymwkvxaehkh.supabase.co";
const SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3aW92c2ZrbXltd2t2eGFlaGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTEzNTE0MjEsImV4cCI6MjEwNjkyNzQyMX0.gEo2azUF1x3gwVG7h8NCDop_ZdjUl41viisIWcK8eI4";
const TABLE_NAME="absensi_v2";
const supa=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
let toastTimer;const toast=m=>{const t=$("toast");clearTimeout(toastTimer);t.textContent=m;t.classList.add("show");toastTimer=setTimeout(()=>t.classList.remove("show"),2500);}
const openL=()=>{$("loginModal").classList.add("show")},closeL=()=>$("loginModal").classList.remove("show");
const escapeHtml=s=>String(s??"").replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let all=[], userRole="guru", isDeveloper=false, currentEmail="", isSyncing=false;
const GURU_MAPEL={"FAUZUL AZMI, S.Sos":["BIOLOGI"],"DESWA YODI EKA PUTRA, S.Pd":["SOSIOLOGI"],"ROSELA, S.H":["PENDIDIKAN PANCASILA dan KEWARGANEGARAAN (PPKn)","SEJARAH"],"MERI ANDAYANI, S.Pd":["MATEMATIKA WAJIB","MATEMATIKA TINGKAT LANJUT"],"IRZA LIANA PITRI, S.Sos":["BUDAYA MELAYU RIAU (BMR)"],"ACI WINARTI, S.Pd.I":["PENDIDIKAN AGAMA ISLAM (PAI)"],"SUNARNI, S.Pd":["SENI BUDAYA","PRAKARYA"],"BONIKA, S.Pd":["PENDIDIKAN JASMANI, OLAHRAGA dan KESEHATAN (PJOK)"],"YUNI PUSPITASARI, S.Pd":["BAHASA INGGRIS"],"ANITA SAPUTRI, S.E":["BAHASA INDONESIA","EKONOMI"]};
const MAPEL_GURU={};Object.entries(GURU_MAPEL).forEach(([guru,mapels])=>{ mapels.forEach(m=>{ MAPEL_GURU[m]=guru; }); });
function isiAwal(){const selM=$("fMapel"),selG=$("fGuru");selM.innerHTML='<option value="">Semua Mapel</option>';selG.innerHTML='<option value="">Semua Guru</option>';Object.keys(MAPEL_GURU).forEach(m=>{let o=document.createElement("option");o.value=m;o.textContent=m;selM.appendChild(o);});let oPak=document.createElement("option");oPak.value="PENDIDIKAN AGAMA KRISTEN (PAK)";oPak.textContent="PENDIDIKAN AGAMA KRISTEN (PAK)";oPak.disabled=true;selM.appendChild(oPak);Object.keys(GURU_MAPEL).forEach(g=>{let o=document.createElement("option");o.value=g;o.textContent=g;selG.appendChild(o);});}
function normalStatus(s){if(!s)return "-";s=s.toString().trim().toLowerCase();if(["alpha","alfa","alpa","a"].includes(s))return "Alfa";if(["hadir","h"].includes(s))return "Hadir";if(["izin","ijin","i"].includes(s))return "Izin";if(["sakit","s"].includes(s))return "Sakit";return s.charAt(0).toUpperCase()+s.slice(1);}
function parseTanggalToISO(tgl){if(!tgl)return "";tgl=tgl.toString().trim();if(/^\d{4}-\d{2}-\d{2}$/.test(tgl))return tgl;const bm={januari:'01',februari:'02',maret:'03',april:'04',mei:'05',juni:'06',juli:'07',agustus:'08',september:'09',oktober:'10',november:'11',desember:'12'};const m=tgl.toLowerCase().match(/(\d{1,2})\s+(januari|februari|maret|april|mei|juni|juli|agustus|september|oktober|november|desember)\s+(\d{4})/);if(m)return `${m[3]}-${bm[m[2]]}-${String(m[1]).padStart(2,'0')}`;const d=new Date(tgl);if(!isNaN(d))return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return "";}
function formatTanggalCantik(tgl){const iso=parseTanggalToISO(tgl);if(!iso)return tgl||"-";const d=new Date(iso+"T00:00:00");if(isNaN(d))return tgl;const hari=["Minggu","Senin","Selasa","Rabu","Kamis","Jum'at","Sabtu"][d.getDay()];const bulan=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"][d.getMonth()];return `${hari}, ${String(d.getDate()).padStart(2,'0')} ${bulan} ${d.getFullYear()}`;}
function formatJamCantik(jam){if(!jam)return "-";let j=jam.toString().replace(/ WIB/gi,"").trim().replaceAll(".",":");return j+" WIB";}
function onDateChange(){const el=$("fTanggal"),wrap=$("dateWrap");if(el.value)wrap.classList.add("has-value");else wrap.classList.remove("has-value");render();}
function setAuthUI(isLogin,role="guru"){userRole=role;isDeveloper=(role==="developer");const dd=$("dashData");dd.classList.toggle('hidden',!isLogin);dd.style.display=isLogin?'block':'none';$("btnLogin").classList.toggle('hidden',isLogin);$("btnLogout").classList.toggle('hidden',!isLogin);if(isLogin){$("roleInfo").innerHTML=isDeveloper?`<span class="roleBadge role-dev">🧑🏻‍💻 DEV</span>`:`<span class="roleBadge role-guru">👨‍🏫 GURU</span>`;$("headerDesc").innerHTML=`mode ${$("roleInfo").innerHTML} - ${escapeHtml(currentEmail)}`;}else{$("roleInfo").innerHTML="";$("headerDesc").textContent="Login untuk akses data";}}
async function login(){const e=$("email").value.trim(),p=$("pass").value.trim(),errBox=$("eLogin");const warn=m=>{errBox.textContent=m;errBox.style.display="block";setTimeout(()=>errBox.style.display="none",3000)};if(!e||!p)return warn("Email & password wajib");errBox.textContent="⏳ Memeriksa...";errBox.style.display="block";const {data,error}=await supa.auth.signInWithPassword({email:e,password:p});if(error){warn("❌ Salah! "+error.message);return;}const role=data.user.app_metadata?.role||"guru";currentEmail=data.user.email;errBox.style.display="none";closeL();$("email").value="";$("pass").value="";setAuthUI(true,role);load();toast(role==="developer"?"🧑🏻‍💻 Developer":"👨‍🏫 Guru");}
async function logout(){await supa.auth.signOut();currentEmail="";setAuthUI(false);all=[];renderStats();render();}
async function load(){const {data,error}=await supa.from(TABLE_NAME).select("*").order("created_at",{ascending:false});if(error){toast("Gagal load: "+error.message);return;}all=data||[];render();renderStats();}
function renderStats(){$("cHadir").textContent=all.filter(d=>normalStatus(d.status)==="Hadir").length;$("cIzin").textContent=all.filter(d=>normalStatus(d.status)==="Izin").length;$("cSakit").textContent=all.filter(d=>normalStatus(d.status)==="Sakit").length;$("cAlfa").textContent=all.filter(d=>normalStatus(d.status)==="Alfa").length;}
function getFiltered(){
  let d=[...all];
  if($("fNama").value) d=d.filter(x=>x.nama?.toLowerCase().includes($("fNama").value.toLowerCase()));
  if($("fStatus").value) d=d.filter(x=>normalStatus(x.status)===normalStatus($("fStatus").value));
  if($("fMapel").value &&!$("fMapel").value.includes("PAK")) d=d.filter(x=>(x.mapel||"")=== $("fMapel").value);
  if($("fGuru").value) d=d.filter(x=>(x.guru||"")=== $("fGuru").value);
  if($("fTanggal").value){ const picked=$("fTanggal").value; d=d.filter(x=>parseTanggalToISO(x.tanggal)===picked); }
  d.sort((a,b)=> (a.nama||"").toLowerCase().localeCompare((b.nama||"").toLowerCase()));
  return d;
}
function render(){
  const d=getFiltered();
  const guruVal=$("fGuru").value;const mapelVal=$("fMapel").value;
  $("infoFilter").textContent=`Menampilkan ${d.length}/${all.length} | ${guruVal||"Semua Guru"} - ${mapelVal||"Semua Mapel"}`;
  const rekapArea=$("rekapArea");
  if((guruVal||mapelVal)&&d.length>0){rekapArea.classList.remove("hidden");if(guruVal&&mapelVal){const hadir=d.filter(x=>normalStatus(x.status)==="Hadir").length;const izin=d.filter(x=>normalStatus(x.status)==="Izin").length;const sakit=d.filter(x=>normalStatus(x.status)==="Sakit").length;const alfa=d.filter(x=>normalStatus(x.status)==="Alfa").length;rekapArea.innerHTML=`<div class="rekapBox"><h4>📚 ${escapeHtml(mapelVal)}</h4><div style="font-size:12px;line-height:1.8">Hadir: ${hadir} | Izin: ${izin} | Sakit: ${sakit} | Alfa: ${alfa}<br><b>Total: ${d.length} siswa</b></div></div>`;}else{let key=guruVal?"mapel":"guru";let icon=guruVal?"📚":"👨‍🏫";const groups={};d.forEach(x=>{const k=x[key]||"Tanpa "+key;if(!groups[k])groups[k]={Hadir:0,Izin:0,Sakit:0,Alfa:0,total:0};const st=normalStatus(x.status);if(groups[k][st]!==undefined)groups[k][st]++;groups[k].total++;});rekapArea.innerHTML=Object.entries(groups).map(([k,v])=>`<div class="rekapBox"><h4>${icon} ${escapeHtml(k)}</h4><div style="font-size:12px;line-height:1.8">Hadir: ${v.Hadir} | Izin: ${v.Izin} | Sakit: ${v.Sakit} | Alfa: ${v.Alfa}<br><b>Total: ${v.total} siswa</b></div></div>`).join("");}}else{rekapArea.classList.add("hidden");rekapArea.innerHTML="";}
  $("tbody").innerHTML=d.map(x=>{
    const st=normalStatus(x.status);const jamInput=x.jam?x.jam.toString().substring(0,5).replace(".",":"):"";const tglCantik=formatTanggalCantik(x.tanggal);const jamCantik=formatJamCantik(x.jam);const mapel=x.mapel||"-",guru=x.guru||"-";
    if(isDeveloper){
      return `<tr>
        <td><input class="editInput" style="width:90px" value="${escapeHtml(x.nama)}" onchange="editField('${x.id}','nama',this.value)"></td>
        <td><div style="display:flex;flex-direction:column;gap:4px"><select class="editInput" style="width:75px" onchange="editField('${x.id}','status',this.value)"><option ${st==="Hadir"?"selected":""}>Hadir</option><option ${st==="Izin"?"selected":""}>Izin</option><option ${st==="Sakit"?"selected":""}>Sakit</option><option ${st==="Alfa"?"selected":""}>Alfa</option></select><span class="badge ${escapeHtml(st)}" style="font-size:9px;width:fit-content">${escapeHtml(st)}</span></div></td>
        <td><div style="display:flex;flex-direction:column;gap:4px"><select class="editInput" style="width:115px" onchange="editGuru('${x.id}',this.value)"><option value="">-</option>${Object.keys(GURU_MAPEL).map(g=>`<option ${g===guru?"selected":""}>${escapeHtml(g)}</option>`).join("")}</select><span class="badge badge-guru" style="font-size:9px;width:fit-content">${escapeHtml(guru)}</span></div></td>
        <td><div style="display:flex;flex-direction:column;gap:4px"><select class="editInput" style="width:115px" onchange="editMapel('${x.id}',this.value)"><option value="">-</option>${Object.keys(MAPEL_GURU).map(m=>`<option ${m===mapel?"selected":""}>${escapeHtml(m)}</option>`).join("")}</select><span class="badge badge-mapel" style="font-size:9px;width:fit-content">${escapeHtml(mapel)}</span></div></td>
        <td><div style="display:flex;flex-direction:column;gap:4px"><input type="date" class="editInput" style="width:110px" value="${escapeHtml(parseTanggalToISO(x.tanggal))}" onchange="editField('${x.id}','tanggal',this.value)"><span style="font-size:10px;font-weight:700">${tglCantik}</span></div></td>
        <td><div style="display:flex;flex-direction:column;gap:4px"><input type="time" class="editInput" style="width:80px" value="${jamInput}" onchange="editJam('${x.id}',this.value)"><span style="font-size:10px;font-weight:700">${jamCantik}</span></div></td>
        <td><button onclick="hapusSatu('${x.id}')" style="border:2px solid #2d1b4e;border-radius:8px;background:#ff5a5f;color:#fff;padding:6px 10px;font-weight:700">🗑️</button></td></tr>`;
    } else {
      return `<tr><td><b>${escapeHtml(x.nama)}</b></td><td><span class="badge ${escapeHtml(st)}">${escapeHtml(st)}</span></td><td><span class="badge badge-guru">${escapeHtml(guru)}</span></td><td><span class="badge badge-mapel">${escapeHtml(mapel)}</span></td><td>${tglCantik}</td><td>${jamCantik}</td><td><button onclick="hapusSatu('${x.id}')" style="border:2px solid #2d1b4e;border-radius:8px;background:#ff5a5f;color:#fff;padding:6px 10px;font-weight:700">🗑️</button></td></tr>`;
    }
  }).join("") || `<tr><td colspan=7 style="text-align:center;border:0;color:#6b5b8a">Tidak ada data</td></tr>`;
}
async function editField(id,field,v){if(!isDeveloper) return toast("🔒 Developer only");if(v.includes("PAK")) return toast("❌ PAK tidak ada guru");const {error}=await supa.from(TABLE_NAME).update({[field]:v}).eq("id",id);if(error)toast("❌ "+error.message);else{toast("✅ "+field+" diubah");load();}}
async function editMapel(id,mapelBaru){if(!isDeveloper) return toast("🔒 Developer only");if(!mapelBaru) return toast("❌ Mapel kosong");if(mapelBaru.includes("PAK")) return toast("❌ PAK tidak ada guru");const guruBaru=MAPEL_GURU[mapelBaru];if(!guruBaru) return toast("❌ Guru tidak ditemukan");const {error}=await supa.from(TABLE_NAME).update({mapel:mapelBaru,guru:guruBaru}).eq("id",id);if(error)toast("❌ "+error.message);else{toast(`📚 ${mapelBaru} → ${guruBaru}`);load();}}
async function editGuru(id,guruBaru){if(!isDeveloper) return toast("🔒 Developer only");if(!guruBaru) return toast("❌ Guru kosong");const listMapel=GURU_MAPEL[guruBaru]||[];const row=all.find(x=>x.id===id);let mapelBaru=row?.mapel;if(!listMapel.includes(mapelBaru)){mapelBaru=listMapel[0]||"";}const {error}=await supa.from(TABLE_NAME).update({guru:guruBaru,mapel:mapelBaru}).eq("id",id);if(error)toast("❌ "+error.message);else{toast(`👨‍🏫 ${guruBaru} → ${mapelBaru}`);load();}}
async function editJam(id,v){if(!isDeveloper)return;const jamLengkap=v.length===5?v+":00":v;const {error}=await supa.from(TABLE_NAME).update({jam:jamLengkap}).eq("id",id);if(error)toast("❌ "+error.message);else{toast("✅ Jam diubah");load();}}
async function hapusSatu(id){if(!confirm("Hapus?"))return;const {error}=await supa.from(TABLE_NAME).delete().eq("id",id);if(error)toast("❌ "+error.message);else{toast("Terhapus");load();}}
function resetFilter(){$("fTanggal").value="";$("dateWrap").classList.remove("has-value");$("fNama").value="";$("fStatus").value="";isiAwal();render();}
async function hapusSemua(){if(!confirm("Hapus semua yang terfilter?"))return;const d=getFiltered();for(let x of d) await supa.from(TABLE_NAME).delete().eq("id",x.id);toast("Terhapus semua");load();}
async function downloadExcel(){const d=getFiltered();if(!d.length){toast("Tidak ada data");return;}const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet("Absensi V2");const HEADER=["NAMA","STATUS","GURU","MAPEL","TANGGAL","JAM"];const FILLS=["FFFFE26A","FFB4F8C8","FFFF8A65","FFD8B4FE","FFFFDA77","FFA0E7E5"];const WIDTHS=[22,14,30,42,34,18];const hRow=ws.addRow(HEADER);hRow.height=28;WIDTHS.forEach((w,i)=>ws.getColumn(i+1).width=w);hRow.eachCell((cell,col)=>{cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:FILLS[col-1]}};cell.font={bold:true,size:12,color:{argb:"FF2D1B4E"}};cell.alignment={horizontal:'center',vertical:'middle',wrapText:true};cell.border={top:{style:'medium',color:{argb:'FF2D1B4E'}},left:{style:'medium',color:{argb:'FF2D1B4E'}},bottom:{style:'medium',color:{argb:'FF2D1B4E'}},right:{style:'medium',color:{argb:'FF2D1B4E'}}};});d.forEach(r=>{const row=ws.addRow([r.nama||"",normalStatus(r.status),r.guru||"",r.mapel||"",formatTanggalCantik(r.tanggal),formatJamCantik(r.jam)]);row.eachCell(c=>{c.alignment={horizontal:'center',vertical:'middle',wrapText:true};c.font={size:11,color:{argb:"FF2D1B4E"}};c.border={top:{style:'medium',color:{argb:'FF2D1B4E'}},left:{style:'medium',color:{argb:'FF2D1B4E'}},bottom:{style:'medium',color:{argb:'FF2D1B4E'}},right:{style:'medium',color:{argb:'FF2D1B4E'}}};});});const buf=await wb.xlsx.writeBuffer();const blob=new Blob([buf],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`absensi-v2-${$("fTanggal").value||new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove();},1000);toast("✅ Excel OK!");}
$("fGuru").addEventListener("change", ()=>{if(isSyncing) return;isSyncing=true;const guru=$("fGuru").value;const selM=$("fMapel");if(!guru){isiAwal();isSyncing=false;render();return;}const mapels=GURU_MAPEL[guru]||[];selM.innerHTML='';mapels.forEach(m=>{let o=document.createElement("option");o.value=m;o.textContent=m;selM.appendChild(o);});if(mapels.length>0) selM.value=mapels[0];toast(`👨‍🏫 ${guru} → ${mapels.join(", ")}`);isSyncing=false;render();});
$("fMapel").addEventListener("change", ()=>{if(isSyncing) return;isSyncing=true;const mapel=$("fMapel").value;const selG=$("fGuru");if(!mapel){isiAwal();isSyncing=false;render();return;}if(mapel.includes("PAK")){toast("❌ PAK tidak ada guru, tidak bisa dipilih");$("fMapel").value="";isSyncing=false;render();return;}const guru=MAPEL_GURU[mapel];selG.innerHTML='';if(guru){let o=document.createElement("option");o.value=guru;o.textContent=guru;selG.appendChild(o);selG.value=guru;toast(`📚 ${mapel} → ${guru}`);}isSyncing=false;render();});
isiAwal();
(async()=>{const {data}=await supa.auth.getSession();if(data.session){const role=data.session.user.app_metadata?.role||"guru";currentEmail=data.session.user.email;setAuthUI(true,role);load();}else{setAuthUI(false);renderStats();render();}})();